# Generated by Django 4.1.1 on 2022-09-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_delete_userdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
